### ISSUE TITLE
Systray icons missing/not displayed

### ISSUE THREAD

**Issue by stefonarch** [jlindgren90/qmpanel#2]
Items are present, tooltips and right click is working and space is reserved but many icons are invisible. Not found/not displayed here are:
Element-desktop, meteo-qt, lxqt-powermanagement, copyQ, cmst, strawberry

Working: telegram,feathernotes, redshift/gammastep, lxqt-notificationd, qbittorrent

**Comment by jlindgren90** [comment]
Thanks. I'm almost certain this is because of using IconPixmap instead of icon names. I know at least lxqt-powermanagement generates icons on-the-fly to illustrate the battery level. It shouldn't be too hard to fix since the coffee is there in lxqt-panel, just needs some TLC.

**Comment by jlindgren90** [comment]
> coffee is there

Autocorrect for the win. Should say "code is there" but that's too funny and I'm leaving it.

**Comment by jlindgren90** [comment]
@stefonarch see if ea2946c2d7d86595067820c372d898adc24dc0e6 fixes this for you.

**Comment by stefonarch** [comment]
It does indeed:
![screen_area_mar_09:24:52_](https://github.com/jlindgren90/qmpanel/assets/10681413/b46896bf-fae1-4b7d-97fd-d73dae5fa0aa)
