### ISSUE TITLE
Calendar pops up as  normal window if panel has no focus before

### ISSUE THREAD

**Issue by stefonarch** [jlindgren90/qmpanel#3]
1. Click on the panel, click clock → calendar opens beneath clock (with bottom panel at screen border as any other popup too - which is another issue also with lxqt-panel)
 2. Focus any other app, click clock → calendar opens as normal window at center screen with decorations.

**Comment by jlindgren90** [comment]
What window manager are you using?

**Comment by stefonarch** [comment]
Sorry forgot to mention "under wayland"; labwc. I assume this issue is not present in x11.

**Comment by jlindgren90** [comment]
Ah okay. Running natively or under XWayland?

**Comment by jlindgren90** [comment]
This should be fixed in master now with the (experimental) layer-shell support.

**Comment by stefonarch** [comment]
In fact it is, nice!
Missing taskbar support in wayland and right click menus in statusnotifier items.

**Comment by jlindgren90** [comment]
Taskbar support is implemented too, but only for wlroots-based compositors (there is no standard Wayland protocol for this).
Most SNI applets (those that use the "Menu" property) should pop up a menu on left-click.

I'm tracking remaining Wayland issues in #7.

**Comment by stefonarch** [comment]
> Taskbar support is implemented too, but only for wlroots-based compositors

I see, don't know why it didn't show up on my first trial.
