### ISSUE TITLE
Add advance documentation / wiki.

### ISSUE THREAD

**Issue by lidgnulinux** [jlindgren90/qmpanel#4]
Hello, I found your panel yesterday and just tried it today. It's great, is there any documentation / wiki I could follow or any complete example config ? Thanks.

**Comment by jlindgren90** [comment]
There is an example config in the README (toward the bottom). Other than that there isn't too much to document, it should "just work". If you have suggestions how to improve the documentation, those are welcome.

**Comment by jlindgren90** [comment]
I think I'll close this -- pull requests to improve the documentation are certainly welcome!
