### ISSUE TITLE
Segmentation fault on pure wayland environment.

### ISSUE THREAD

**Issue by lidgnulinux** [jlindgren90/qmpanel#5]
Allow me to report that qmpanel seems still get segfault on wayland (x11 is fine). I'm trying it on some wayland compositors and get same result. It suspicious since the compilation.

```
WARNING: CMake: Dependency Qt5::X11Extras for KF5WindowSystem was not found
Run-time dependency kf5windowsystem found: YES 5.112.0
```

But the compilation is done successfully.

When I run the qmpanel I got this :

```
[qmpanel]$ QT_QPA_PLATFORM=wayland b/qmpanel
kf.windowsystem: Could not find any platform plugin
Segmentation fault
```
Any clue to fix it ? Thanks

**Comment by jlindgren90** [comment]
Pure Wayland is not supported yet. Patches welcome.

**Comment by jlindgren90** [comment]
The segfault should be fixed with https://github.com/jlindgren90/qmpanel/commit/513ff156bc9df085568b44a3b4fc5944746271e4.

I'll go ahead and close this, but note that native Wayland support is still very much a work in progress.
