### ISSUE TITLE
Disable taskbar buttons

### ISSUE THREAD

**Issue by txtsd** [jlindgren90/qmpanel#9]
Will it be possible to add a config option to disable the taskbar buttons?

I just want the app menu, the tray icons, and the clock.

**Comment by jlindgren90** [comment]
Hi @txtsd, thanks for your interest in the project! I'm not currently planning to support other panels layouts besides the default.

You could try to do it yourself - it probably would be just a small code change to disable the taskbar unconditionally - or you could look into lxqt-panel, which is the project I used as a starting point. I believe it supports more different layouts.

**Comment by txtsd** [comment]
That is fair. Thank you.
